language: go

sudo: required

go:
- 1.x
- 1.10.x
- 1.11.x
- 1.12.x
- master

matrix:
  allow_failures:
  - go: master

before_install:
# rename package name for imports
- mv $HOME/gopath/src/github.com/Vehsamrak $HOME/gopath/src/github.com/vehsamrak

# download dependencies
- go get -t -v ./...

script:
# run unit tests with coverage
- bash <(curl -s https://raw.githubusercontent.com/vehsamrak/go-multi-package-coverage/1.1.0/test.sh)

# run integration tests
- go test -v ./test/integration/...

after_success:
# publish coverage report
- bash <(curl -s https://codecov.io/bash)
